### ISSUE TITLE
my front page is always loading....

### ISSUE THREAD

**Issue by kk456852** [weibenfalk/jwtToken-react-express#1]
after  runing the npm install and npm start,  my chrome open a webpage automatically and it just show me " lodaing ````"

**Comment by weibenfalk** [comment]
Can't recreate the error ... just tried it out. Does the console give you an error?

**Comment by kk456852** [comment]
> Can't recreate the error ... just tried it out. Does the console give you an error?

oh.... it's my mistake.  I was running frontend's script  without  running server.  thanks for your reply.
